
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 07 16:48:15 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRACKET = 6;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int EQUAL = 7;
  public static final int NUMBER = 4;
  public static final int MINUS = 3;
  public static final int OBRACKET = 5;
  public static final int EOF = 0;
}
