
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 08 23:01:35 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EMAIL = 3;
  public static final int error = 1;
  public static final int TOKEN2 = 2;
  public static final int TOKEN1 = 4;
  public static final int EOF = 0;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[3]=new String("EMAIL");
		TT[1]=new String("error");
		TT[2]=new String("TOKEN2");
		TT[4]=new String("TOKEN1");
		TT[0]=new String("EOF");
	}
public String getTT(int i){return TT[i];}
}
