
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 01 16:35:40 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 36;
  public static final int SO = 16;
  public static final int MAJ = 23;
  public static final int S = 17;
  public static final int DOUBLE = 3;
  public static final int SC = 14;
  public static final int INT = 2;
  public static final int MINUS = 19;
  public static final int STAR = 20;
  public static final int STATIC = 38;
  public static final int NOT = 31;
  public static final int AND = 29;
  public static final int CM = 15;
  public static final int OR = 30;
  public static final int DIV = 21;
  public static final int RO = 10;
  public static final int EXTERN = 39;
  public static final int MIN_EQ = 24;
  public static final int PLUS = 18;
  public static final int MIN = 22;
  public static final int IF = 6;
  public static final int ID = 4;
  public static final int EOF = 0;
  public static final int EQ_MAJ = 27;
  public static final int error = 1;
  public static final int RC = 11;
  public static final int UNSIGNED = 35;
  public static final int INT_TYPE = 32;
  public static final int BO = 12;
  public static final int EQ = 28;
  public static final int DOUBLE_TYPE = 33;
  public static final int ELSE = 9;
  public static final int SIGNED = 34;
  public static final int BC = 13;
  public static final int WHILE = 7;
  public static final int THEN = 8;
  public static final int LONG = 37;
  public static final int EQ_MIN = 25;
  public static final int MAJ_EQ = 26;
  public static final int PRINT = 5;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[36]=new String("SHORT");
		TT[16]=new String("SO");
		TT[23]=new String("MAJ");
		TT[17]=new String("S");
		TT[3]=new String("DOUBLE");
		TT[14]=new String("SC");
		TT[2]=new String("INT");
		TT[19]=new String("MINUS");
		TT[20]=new String("STAR");
		TT[38]=new String("STATIC");
		TT[31]=new String("NOT");
		TT[29]=new String("AND");
		TT[15]=new String("CM");
		TT[30]=new String("OR");
		TT[21]=new String("DIV");
		TT[10]=new String("RO");
		TT[39]=new String("EXTERN");
		TT[24]=new String("MIN_EQ");
		TT[18]=new String("PLUS");
		TT[22]=new String("MIN");
		TT[6]=new String("IF");
		TT[4]=new String("ID");
		TT[0]=new String("EOF");
		TT[27]=new String("EQ_MAJ");
		TT[1]=new String("error");
		TT[11]=new String("RC");
		TT[35]=new String("UNSIGNED");
		TT[32]=new String("INT_TYPE");
		TT[12]=new String("BO");
		TT[28]=new String("EQ");
		TT[33]=new String("DOUBLE_TYPE");
		TT[9]=new String("ELSE");
		TT[34]=new String("SIGNED");
		TT[13]=new String("BC");
		TT[7]=new String("WHILE");
		TT[8]=new String("THEN");
		TT[37]=new String("LONG");
		TT[25]=new String("EQ_MIN");
		TT[26]=new String("MAJ_EQ");
		TT[5]=new String("PRINT");
	}
public String getTT(int i){return TT[i];}
}
