
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat May 14 11:15:42 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CARET = 14;
  public static final int PLUS = 10;
  public static final int INT = 16;
  public static final int CM = 6;
  public static final int STAR = 12;
  public static final int S = 8;
  public static final int ID_UPP = 3;
  public static final int SO = 5;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int DOT = 7;
  public static final int EQ = 15;
  public static final int SC = 4;
  public static final int QM = 9;
  public static final int ID_LOW = 2;
  public static final int UMINUS = 18;
  public static final int DOUBLE = 17;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[14]=new String("CARET");
		TT[10]=new String("PLUS");
		TT[16]=new String("INT");
		TT[6]=new String("CM");
		TT[12]=new String("STAR");
		TT[8]=new String("S");
		TT[3]=new String("ID_UPP");
		TT[5]=new String("SO");
		TT[0]=new String("EOF");
		TT[13]=new String("DIV");
		TT[11]=new String("MINUS");
		TT[1]=new String("error");
		TT[7]=new String("DOT");
		TT[15]=new String("EQ");
		TT[4]=new String("SC");
		TT[9]=new String("QM");
		TT[2]=new String("ID_LOW");
		TT[18]=new String("UMINUS");
		TT[17]=new String("DOUBLE");
	}
public String getTT(int i){return TT[i];}
}
