
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Apr 30 19:38:15 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C = 8;
  public static final int DATE = 16;
  public static final int LETTER = 15;
  public static final int LI = 10;
  public static final int S = 7;
  public static final int SECT_SEP = 2;
  public static final int EOF = 0;
  public static final int ARROW = 6;
  public static final int BO = 13;
  public static final int AV = 12;
  public static final int ISBN = 4;
  public static final int SO = 14;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int UINT = 9;
  public static final int LS = 11;
  public static final int NAME = 3;
}
