
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 02 15:44:45 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RO = 8;
  public static final int RULE_SEP = 6;
  public static final int INT_SYMBOL = 7;
  public static final int VARIABLE = 3;
  public static final int EOF = 0;
  public static final int ATOM = 2;
  public static final int RC = 9;
  public static final int DOT = 4;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int ERR = 10;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("RO");
		TT[6]=new String("RULE_SEP");
		TT[7]=new String("INT_SYMBOL");
		TT[3]=new String("VARIABLE");
		TT[0]=new String("EOF");
		TT[2]=new String("ATOM");
		TT[9]=new String("RC");
		TT[4]=new String("DOT");
		TT[1]=new String("error");
		TT[5]=new String("COMMA");
		TT[10]=new String("ERR");
	}
public String getTT(int i){return TT[i];}
}
